### ISSUE TITLE
Cards padding

### ISSUE THREAD

**Issue by minhhbt** [COSC-499-EquiFood-B/EquiFoodApp-B#206]
Center align the food cards

**Comment by NeilanshTriesToCode** [comment]
Changes made in the ``FutureBuilder`` of the ``HmepageWidget`` in the **IndivDash1cont.dart** file:
- Replaced ```ListView.builder``` with ```GridView.builder``` and added the extra arg (``gridDelegate``) associated with it.
- I think that ``ListView`` only renders Cards/Tiles above one another. To have them placed adjacently, we use ``GridView``. So replacing the former with the latter makes sense.
- There is still a padding issue. There is some extra horizontal space which appears to be due to padding. However, the issue remains to be fixed as the exact piece of code causing the extra padding is yet to be found (Couldn't find as of today - will work on another issue for now).

**Comment by NeilanshTriesToCode** [comment]
- Made changes and merged into **develop**. 
- However, there still seems to be a padding issue: there appears to be extra space at the bottom of each Card caused by some bottom padding.
- Haven't been able to find the exact piece of code causing the issue.
- Most padding issues have been solved now though.

_Will keep this issue open and try to resolve the remaining bottom padding problem._

**Comment by minhhbt** [comment]
Yesssss done

**Comment by minhhbt** [comment]
Done
